version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
      python: 3.11
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - sudo yum update -y
      - yum install -y jq
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip ./sonar-scanner-cli-4.7.0.2747-linux.zip
      - export PATH=$PATH:./sonar-scanner-4.7.0.2747-linux/bin/
  build:
    commands:
      - sonar-scanner -Dsonar.login=168a281629314c7bb46eafedd42fa72de4ec12b7 -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=shantanu_shopify -Dsonar.organization=shantanu1911 -DgeneratePom=true
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=shantanu_shopify > result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
