# Generated by Django 5.0 on 2023-12-12 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0010_auto_20211204_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='hindiname',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hindiname',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
